### PR TITLE
make cache keys more unique to prevent collisions

### PR DESCRIPTION
**Pull request by ThomasN231**
**What issue does this PR address?**
[bug 283](https://github.com/DuendeSoftware/IdentityServer/issues/283)

**Important: Any code or remarks in your Pull Request are under the following terms:**

If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose, including to make and sell any products and services.

(see [our license](https://duendesoftware.com/license/identityserver.pdf), section 7)

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks! Is this blocking you right now?

**Comment by ThomasN231** [comment]
Nope, more an inconvenience right now since the underlying feature is not widely used in production right now.

**Comment by brockallen** [comment]
@ThomasN231, I submitted a different PR to address this. I feel it will address your issue, but please have a look to confirm. Thanks.

https://github.com/DuendeSoftware/IdentityServer/pull/315

**Comment by brockallen** [comment]
We'll close this, since the other was merged.

**Pull request closed without merging**
