### PR TITLE
Make ServerSideSessionStore.GetAndRemoveExpiredSessionsAsync virtual

### PR DESCRIPTION
**Pull request by AndersAbel**
#1433

### CODE REVIEW

**Review by brockallen — APPROVED** [review]

**Comment by brockallen** [comment]
@AndersAbel do you know the urgency of releasing this (IOW, was a customer waiting)?

**Comment by AndersAbel** [comment]
I don't think it's that urgent, they are still early in the implementation phase. I'll check with them.

**Comment by josephdecock** [comment]
Did we ever decide if we were going to do a 6.3.6 release for this? It is in both 6.3.x and main, so it will go out in our 7.0 preview 2 this week.

**Comment by AndersAbel** [comment]
I don't think there's any need to make a 6.3.6 just for this. I think it can wait for the next 6.3.x patch release.

**Comment by brockallen** [comment]
IIRC we did release this into the 6.3.6 patch already.

**Comment by josephdecock** [comment]
Yeah, I was confused because because it wasn't in our github releases, but that's fixed now.

**Pull request merged**
