### PR TITLE
Split OpenTelemetry traces into finer grained sources

### PR DESCRIPTION
**Pull request by leastprivilege**
Separates OTel traces into finer grained sources like base, store, caching, validation

### CODE REVIEW

**Comment by leastprivilege** [comment]
When everything is turned on - you get the full details (and with this new approach probably even more)

Screenshot 2022-03-16 at 10 22 45

...and when only `base` is activated:

Screenshot 2022-03-16 at 10 23 40

**Comment by brockallen** [comment]
Base or Core?

**Comment by brockallen** [comment]
Basic

**Comment by leastprivilege** [comment]
Done. 

please approve ;)

**Review by brockallen — APPROVED** [review]

**Pull request merged**
