### PR TITLE
Move all files into /identity-server

### PR DESCRIPTION
**Pull request by damianh**
- In preparation to merge all commercial products into a single repository, move the IdentityServer codebase into `/identity-server`. 
- GitHubActions workflows paths adjusted accordingly.

**Important: Any code or remarks in your Pull Request are under the following terms:**

If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose, including to make and sell any products and services.

(see [our license](https://duendesoftware.com/license/identityserver.pdf), section 7)

### CODE REVIEW

**Comment by damianh** [comment]
@josephdecock Rebase this branch as the PRs etc close off. This PR does need merging before being able to merge in the other respositories.

**Comment by josephdecock** [comment]
@SimonCropp we're trying to reorganize the repo in this PR. We appreciate all your contributions, but we're trying to close all the open PRs so that this can land cleanly. Can you hold off on more contributions for a bit please?

**Comment by SimonCropp** [comment]
LOL. sorry. feel free to kill any of my prs. i can always resubmit them

**Comment by SimonCropp** [comment]
anything i can help with?

**Review by josephdecock — APPROVED** [review]
codeql issues flagged here are not new

**Pull request merged**
