### PR TITLE
Fix identation

### PR DESCRIPTION
**Pull request by AndersAbel**

### CODE REVIEW

**Comment by brockallen** [comment]
Do the other hosts also need this fix?

**Comment by AndersAbel** [comment]
No, not the indentation, they do not have the same oTel code. Should I copy it over so all the hosts have the same OTel code?

**Review by brockallen — APPROVED** [review]

**Comment by brockallen** [comment]
Hmm, merge conflicts?

**Review by josephdecock — APPROVED** [review]

**Comment by brockallen** [comment]
@AndersAbel check the build failures. there's a security issue in a dependency:

/Users/runner/work/IdentityServer/IdentityServer/hosts/EntityFramework/Host.EntityFramework.csproj : error NU1902: Warning As Error: Package 'OpenTelemetry.Instrumentation.AspNetCore' 1.5.1-beta.1 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-vh2m-22xx-q94f [/Users/runner/work/IdentityServer/IdentityServer/Duende.IdentityServer.sln]

**Comment by AndersAbel** [comment]
@brockallen The build failures is independent of this. I'll create another PR for the packages.

**Pull request merged**
