### PR TITLE
Fix null reference exception in event service when httpcontext missing

### PR DESCRIPTION
**Pull request by josephdecock**
Fixes https://github.com/DuendeSoftware/Support/issues/614, which seems to have reappeared for events.

### CODE REVIEW

**Review by brockallen — APPROVED** [review]

**Comment by brockallen** [comment]
mainline or 7.0.x branch?

**Comment by josephdecock** [comment]
> mainline or 7.0.x branch?

7.0.x - I've rebased...

**Comment by josephdecock** [comment]
Hmm, now too many commits are here

**Comment by josephdecock** [comment]
Okay, all better now.

**Pull request merged**
