### PR TITLE
Filter out expected ef migration exception

### PR DESCRIPTION
**Pull request by josephdecock**
Filter out exceptions that we expect to see during migrations in the asp.net identity and EF hosts. We already do this in the quickstart tutorial samples.

Should help folks who encounter problems like this: https://github.com/DuendeSoftware/Support/issues/678

### CODE REVIEW

**Comment by brockallen** [comment]
.NET 8 is coming soon, and they expose that exception type, right? Maybe this should use that new one (once we update our dependencies)?

**Comment by brockallen** [comment]
Or was the OP using this host as the starter/sample?

**Comment by josephdecock** [comment]
I was thinking we'd include this in the templates for now, and switch to StopTheHostException for the next release.

**Comment by brockallen** [comment]
This is in the template already, and we're going to re-do for .NET 8 soon anyway.

**Pull request closed without merging**
