### PR TITLE
remove redundant Distinct

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by josephdecock** [comment]
I don't think we can prove with certainty that these calls to Distinct are always redundant. We also have merge conflicts here, and in the interest of trying to clear out all the PRs so that we can merge https://github.com/DuendeSoftware/IdentityServer/pull/1653, I'm just going to close this one.

**Comment by SimonCropp** [comment]
@josephdecock they are being added to a hashset. so the distinct is redundant?

**Comment by josephdecock** [comment]
The `AllowedAccessTokenSigningAlgorithms` that this is called on is an `ICollection<string>` with a default value that is a `HashSet`, so while it is true that in the vast majority of cases the call is redundant, it is possible that some caller creates a different ICollection and then messes up by duplicating values in it.

**Comment by SimonCropp** [comment]
i dont think so. the loop does a dictionary contains check on the type

**Comment by josephdecock** [comment]
If you add a unit test that verifies that the results are distinct, then we can merge. But please hold off until after The Big Merge. Thanks!

**Pull request closed without merging**
