### PR TITLE
Refactor DefaultTokenCreationService

### PR DESCRIPTION
**Pull request by stefannikolei**
* Use ValueTask where appropriate
* spawn Tasks and await later where appropriate
* create a static instance of JsonWebTokenHandler. It does not save any instance data and thus does not need to be created every single time

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks! We will re-visit when we drop .NET Core 3.1 - i am not a huge fan of ifdefs...

**Comment by stefannikolei** [comment]
If you want I can drop the ifdefs to get the rest in?

**Comment by leastprivilege** [comment]
We switch to target .NET 6 - feel free to update...

**Comment by stefannikolei** [comment]
@leastprivilege i updated it

**Comment by stefannikolei** [comment]
@leastprivilege Did you have a chance to have a look at it. Is there anything I need to tweak?

**Comment by brockallen** [comment]
Thanks for this, but we're not in a position to accept this PR. Thanks.

**Pull request closed without merging**
